spring:
  profiles:
    name: test-YAML
    environment: test
    notificacionEventos: "https://fz73xehwah.execute-api.us-east-1.amazonaws.com/dev/notificacion/api/v1/mensajeria/eventos/mensajes"
    calculadoraLiquidacion: "https://fz73xehwah.execute-api.us-east-1.amazonaws.com/dev/poliza/api/v1/siniestros/calculadora"
    crearSiniestroSimon: "https://fz73xehwah.execute-api.us-east-1.amazonaws.com/dev/poliza/api/v1/siniestros"
    consultaValorReserva: "https://fz73xehwah.execute-api.us-east-1.amazonaws.com/dev/poliza/api/v1/siniestros/reservas"
  jpa:    database: mysql
    show-sql: true

  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable_pruebas?autoReconnect=true&serverTimezone=America/Bogota&nullCatalogMeansCurrent=true
    username: Desarrollo
    password: Segurosb123

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Bogota
    date-format: yyyy-MM-dd HH:mm:ss

indemnizaciones:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/indemnizaciones?autoReconnect=true&serverTimezone=America/Bogota&nullCatalogMeansCurrent=true
    username: Desarrollo
    password: Segurosb123
  jpa:
    database: mysql
    show-sql: true



server:
  port: 80
  address: 0.0.0.0
  servlet:
    context-path: /flujos-indemnizaciones
    
   
management:
  endpoints:
    web:
      base-path: /health

info:
  status: UP
  
  
variable:
  name:
    reintentos: 3
  notificacionEventos:
    crearCaso:
      aplicacion: "J0ETQ70N6H8ELEY"
      evento: "LPSEQMW2DH7J8OO"

springdoc:
  swagger-ui:
    path:swagger-ui.html
    